# Generated by Django 3.0.5 on 2020-05-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.TextField(max_length=1000)),
                ('status', models.BooleanField(blank=True, default=0, null=True)),
            ],
        ),
    ]
